### ISSUE TITLE
Гуся-Хрустального??

### ISSUE THREAD

**Issue by jimhucksly** [mfursov/russian-cities#3]
Я житель Гусь-Хрустального! Скажите, откуда вы взяли, что название нашего города склоняется по падежам именно так, как представлено у вас в базе? На самом деле "гусь", как часть названия города, не склоняется, она остается всегда в такой форме!

**Comment by mfursov** [comment]
Проверяйте!

**Comment by jimhucksly** [comment]
вот теперь правильно! Спасибо, а то обидно за свой город)
